# Generated by Django 3.2.7 on 2021-10-05 04:05

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='customer_xid',
            field=models.UUIDField(auto_created=True, db_index=True, default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
