# Generated by Django 3.2.7 on 2021-10-05 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='reference_id',
            field=models.CharField(db_index=True, default='test', max_length=100, unique=True),
            preserve_default=False,
        ),
    ]
