# Generated by Django 3.2.7 on 2021-10-06 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0002_transaction_reference_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='is_deposit',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
