# Generated by Django 3.2.7 on 2021-10-06 17:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('apis', '0003_transaction_is_deposit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wallet',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='wallet',
            name='user',
        ),
        migrations.AddField(
            model_name='wallet',
            name='owned_by',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='customer_wallet', to='accounts.user'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='transaction',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='wallet',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
