# Generated by Django 3.2.7 on 2021-10-07 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0004_auto_20211006_1706'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='status',
            field=models.CharField(choices=[('success', 'success'), ('failed', 'failed')], default='success', max_length=30),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='wallet',
            name='status',
            field=models.CharField(choices=[('enabled', 'enabled'), ('disabled', 'disabled')], db_index=True, default='enabled', max_length=20),
        ),
    ]
